apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lv0vthrnw-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lv0vthrnw-java-quarkus-gitops